
addons:
  apt:
    packages:
    - aria2
    #- gnupg
    - gnupg2
    - graphviz
    - openssl
before_install:
- export JAVA_HOME=/usr/lib/jvm/java-8-oracle
- wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
- bash install-jdk.sh -F 10 -L BCL --target $HOME/oraclejdk10 --workspace $HOME/.cache/install-jdk
- if [ -d /home/travis/oraclejdk10 ]; then sudo mkdir -p /usr/lib/jvm; sudo ln -s /home/travis/oraclejdk10 /usr/lib/jvm/java-10-oracle; fi
- aria2c --file-allocation=none -c -x 10 -s 10 -m 0 --console-log-level=notice --log-level=notice --summary-interval=0 -o apache-maven-3.5.4-bin.zip https://archive.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.zip && unzip -qq apache-maven-3.5.4-bin.zip
- export M2_HOME=$PWD/apache-maven-3.5.4
- export PATH=$M2_HOME/bin:$PATH
- if [ -z "${LOGGING_LEVEL_ROOT}" ]; then export LOGGING_LEVEL_ROOT=INFO; fi
branches:
  only:
  #- master # do nothing on master branch
  - develop # snapshots on develop branch
  - /^feature\/.*$/ # build and test on feature branches
  - /^hotfix\/.*$/ # release on hotfix branches
  - /^release\/.*$/ # release on release branches
  #- /^v\d+\.\d+(\.\d+)?(-\S*)?/ # build and publish a github release (can skip tests here) or do nothing on version tags
cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/.gradle"
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"

dist: trusty
env:
  global:
  # i.e. CI_OPT_CI_SCRIPT=https://github.com/ci-and-cd/maven-build/raw/master/src/main/ci-script/lib_ci.sh
  - CI_OPT_CI_SCRIPT=https://github.com/ci-and-cd/maven-build/raw/master/src/main/ci-script/lib_ci.sh
  - CI_OPT_INFRASTRUCTURE=opensource
  - MAVEN_SKIP_RC=true
group: edge
install: true
jdk:
- oraclejdk8
#- oraclejdk9
language: java
script:
# When prefixed with `travis_wait 30`, no log output until it is done.
# see: https://github.com/travis-ci/travis-ci/issues/4190 or https://github.com/HaxeFoundation/hxcpp/issues/709
- while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
- bash ci.sh mvn clean install sonar:sonar site deploy site-deploy
- kill %1
services:
- docker
sudo: required
