# production configuration

version: '2.1'
services:
  eureka-standalone:
    extends:
      service: base-eureka
      file: docker-compose-base.yml
    container_name: ${CONTAINER_HOST_NAME:-eureka-standalone}
    environment:
    - CONTAINER_HOST_NAME=${CONTAINER_HOST_NAME:-eureka-standalone}
    - EUREKA_CLIENT_FETCHREGISTRY=false
    - EUREKA_CLIENT_REGISTERWITHEUREKA=false
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    - EUREKA_INSTANCE_HOSTNAME=${HOST_IPADDRESS} # ${CONTAINER_HOST_NAME:-eureka-standalone}
    - EUREKA_INSTANCE_IPADDRESS=${HOST_IPADDRESS}
    - EUREKA_INSTANCE_NONSECUREPORT=${SERVER_PORT:-8761}

    - EUREKA_INSTANCE_REGISTRY_DEFAULTOPENFORTRAFFICCOUNT=${EUREKA_INSTANCE_REGISTRY_DEFAULTOPENFORTRAFFICCOUNT:-1}
    - EUREKA_SERVER_ENABLESELFPRESERVATION=${EUREKA_SERVER_ENABLESELFPRESERVATION:-true}
    - EUREKA_SERVER_RENEWALPERCENTTHRESHOLD=${EUREKA_SERVER_RENEWALPERCENTTHRESHOLD:-0.50}
    - LOGGING_LEVEL_ROOT=${LOGGING_LEVEL_ROOT:-INFO}
    - SERVER_PORT=${SERVER_PORT:-8761}
    - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME:-eureka-standalone}
    - SPRING_CLOUD_CLIENT_HOSTNAME=${HOST_IPADDRESS} # ${CONTAINER_HOST_NAME:-eureka-standalone}
    - SPRING_CLOUD_CLIENT_IPADDRESS=${HOST_IPADDRESS}


    - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-staging.env,manual_ip_hostname,port_nonsecure,peer_awareness}

    - SPRING_SECURITY_USER_NAME=${SPRING_SECURITY_USER_NAME:-user}
    - SPRING_SECURITY_USER_PASSWORD=${SPRING_SECURITY_USER_PASSWORD:-user_pass}
    hostname: ${CONTAINER_HOST_NAME:-eureka-standalone}
    network_mode: bridge
    ports:
    - "${SERVER_PORT:-8761}:${SERVER_PORT:-8761}"
    volumes:
    - data:/home/alpine/data
    - tmp:/tmp

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/data
      o: bind
  tmp:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/tmp
      o: bind
