
version: '2.1'
services:
  base-consul-agent:
    build:
      context: .
      dockerfile: Dockerfile
    cap_add: # ignored in swarm mode (docker-compose yaml version 3.x)
    - NET_BIND_SERVICE
    environment:
      CONSUL_ALLOW_PRIVILEGED_PORTS: 1
      CONSUL_BIND_INTERFACE: ${CONSUL_BIND_INTERFACE:-eth0}
      CONSUL_LOCAL_CONFIG: '{"leave_on_terminate": true}'
      CONSUL_RECURSORS: ${CONSUL_RECURSORS:-} # comma split list
      # To avoid loop, must exclude host itself from 'recursors' option, so we need to know host's ip-address.
      HOST_IPADDRESS: ${HOST_IPADDRESS:-}
    image: ${IMAGE_PREFIX:-cloudready}/consul:${IMAGE_TAG:-1.1.0}
    labels:
      top.infra.cloudready.deploy.script.commit-id: ${DEPLOY_SCRIPT_COMMITID}
      top.infra.cloudready.deploy.script.label: ${DEPLOY_SCRIPT_LABEL}
      top.infra.cloudready.deploy.script.repo: ${DEPLOY_SCRIPT_REPO}
      top.infra.cloudready.deploy.config.commit-id: ${DEPLOY_CONFIG_COMMITID}
      top.infra.cloudready.deploy.config.label: ${DEPLOY_CONFIG_LABEL}
      top.infra.cloudready.deploy.config.repo: ${DEPLOY_CONFIG_REPO}
    ports:
    # Server RPC is used for communication between Consul clients and servers
    # for internal request forwarding.
    - "${CONSUL_RPC_PORT:-8300}:8300/tcp"
    # Serf LAN and WAN (WAN is used only by Consul servers) are used for gossip between Consul agents.
    # LAN is within the datacenter
    #- "${CONSUL_LAN_GOSSIP_PORT:-8301}:8301/tcp"
    # WAN is between just the Consul servers in all datacenters.
    #- "${CONSUL_LAN_GOSSIP_PORT:-8301}:8301/udp"
    - "${CONSUL_WAN_GOSSIP_PORT:-8302}:8302/tcp"
    - "${CONSUL_WAN_GOSSIP_PORT:-8302}:8302/udp"
    # HTTP and DNS (both TCP and UDP) are the primary interfaces that applications
    # use to interact with Consul.
    - "${CONSUL_HTTP_API_PORT:-8500}:8500/tcp"
    #- "${CONSUL_DNS_PORT:-8600}:8600/tcp"
    #- "${CONSUL_DNS_PORT:-8600}:8600/udp"
    #privileged: true
    restart: always
#    volumes:
#    # Read host's /etc/resolv.conf to find out DNS servers to set consul's 'recursors' automatically.
#    # Insert 127.0.0.1 at first position if possible (/etc/resolv.conf in OSX is not consulted for resolution).
#    - /etc/resolv.conf:/var/lib/host_etc_resolv.conf
