# base configuration

version: '2.1'
services:
  base-eureka-sidecar:
    command: []
    environment:
    # Mandatory, Address(s) of Eureka node or cluster (comma split)
    - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:-http://user:user_pass@eureka-standalone:8761/eureka/}

    # Optional, Eureka prefer ip address not hostname
    # Change this only when sidecar can not properly register the application with default values and there are issues on service access.
    - EUREKA_INSTANCE_PREFERIPADDRESS=${EUREKA_INSTANCE_PREFERIPADDRESS:-true}

    - LOGGING_LEVEL_ROOT=${LOGGING_LEVEL_ROOT:-INFO}

    # The port of this sidecar, need not to change this if no port conflict.
    - SERVER_PORT=${SERVER_PORT:-5678}

    # Mandatory, The health check URL path of non-JVM application or service
    - SIDECAR_HEALTHURI=${SIDECAR_HEALTHURI:-/health} # implement this URL on the non-JVM application or service.

    # Optional, Homepage of the non-JVM application or service
    #- SIDECAR_HOMEPAGEURI=${SIDECAR_HOMEPAGEURI:-/}

    # Optional, Hostname of the non-JVM application or service. This value will appear in instance-id
    # Change this only when sidecar can not properly register the application with default values and there are issues on service access.
    #- SIDECAR_HOSTNAME=${SIDECAR_HOSTNAME:}

    # Optional, Ip address of the non-JVM application or service. This value will appear in instance-id if SIDECAR_HOSTNAME absent.
    # Change this only when sidecar can not properly register the application with default values and there are issues on service access.
    #- SIDECAR_IPADDRESS=${SIDECAR_IPADDRESS:}

    # Mandatory, The non-JVM application or service's port
    - SIDECAR_PORT=${SIDECAR_PORT:-5678} # change me

    # Mandatory, Application or service name of the non-JVM application or service
    - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME:-the-name-of-non-JVM-application-or-service}

    - SPRING_CLOUD_INETUTILS_PREFERREDNETWORKS=${SPRING_CLOUD_INETUTILS_PREFERREDNETWORKS}
    - SPRING_CLOUD_INETUTILS_IGNOREDINTERFACES=${SPRING_CLOUD_INETUTILS_IGNOREDINTERFACES}

    # Password to access management endpoints such as /env, /health and so on.
    - SECURITY_USER_PASSWORD=${SECURITY_USER_PASSWORD:-} # change me

    image: ${IMAGE_PREFIX:-cloudready}/spring-cloud-eureka-sidecar:${IMAGE_VERSION:-0.0.4-SNAPSHOT}
    labels:
      top.infra.cloudready.deploy.script.commit-id: ${DEPLOY_SCRIPT_COMMITID}
      top.infra.cloudready.deploy.script.label: ${DEPLOY_SCRIPT_LABEL}
      top.infra.cloudready.deploy.script.repo: ${DEPLOY_SCRIPT_REPO}
      top.infra.cloudready.deploy.config.commit-id: ${DEPLOY_CONFIG_COMMITID}
      top.infra.cloudready.deploy.config.label: ${DEPLOY_CONFIG_LABEL}
      top.infra.cloudready.deploy.config.repo: ${DEPLOY_CONFIG_REPO}
    restart: always
